# Generated by Django 2.1.5 on 2019-02-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page_content', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name='Creation Date')),
                ('last_update_date', models.DateTimeField(verbose_name='Last modified at ')),
                ('categories', models.ManyToManyField(to='mysite.Category')),
            ],
            options={
                'ordering': ('page_content',),
            },
        ),
    ]
