# Generated by Django 2.1.5 on 2019-02-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190212_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(default=None, to='mysite.Category'),
        ),
    ]
