# Generated by Django 2.1.5 on 2019-02-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190212_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, to='mysite.Category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
